# Generated by Django 4.2.5 on 2023-09-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pic',
            field=models.CharField(default='', max_length=64, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='career',
            field=models.CharField(default='', max_length=24, verbose_name='职业'),
        ),
    ]
