# Generated by Django 4.2.5 on 2023-09-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', unique=True),
        ),
    ]
