# Generated by Django 4.2.5 on 2023-09-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=64, verbose_name='书名')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('Listing_time', models.DateTimeField(verbose_name='出版时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('type', models.CharField(max_length=32, verbose_name='类型')),
                ('lang', models.CharField(max_length=32, verbose_name='语言')),
                ('publisher', models.CharField(max_length=32, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='定价')),
                ('intro', models.CharField(default='', max_length=512, verbose_name='描述')),
                ('pic', models.CharField(default='', max_length=64, verbose_name='封面')),
            ],
        ),
    ]
