# Generated by Django 4.2.5 on 2023-09-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Listing_time',
            field=models.DateField(verbose_name='出版时间'),
        ),
    ]
