# Generated by Django 4.2.5 on 2023-09-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Listing_time',
            field=models.DateTimeField(verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
