# Generated by Django 4.2.5 on 2023-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_listing_time_alter_book_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.CharField(default='', max_length=64, verbose_name='封面'),
        ),
    ]
